//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCenter
    {
        public int ID { get; set; }
        public string ProductID { get; set; }
        public string ProductTitle { get; set; }
        public Nullable<int> ProductType { get; set; }
        public string CreatetPeople { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string LogoUrl { get; set; }
        public Nullable<int> Language { get; set; }
    }
}
