//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class YingShiDaEntities : DbContext
    {
        public YingShiDaEntities()
            : base("name=YingShiDaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommonQuestion> CommonQuestions { get; set; }
        public virtual DbSet<Company_Culture> Company_Culture { get; set; }
        public virtual DbSet<Company_History> Company_History { get; set; }
        public virtual DbSet<Company_Honor> Company_Honor { get; set; }
        public virtual DbSet<Company_Location> Company_Location { get; set; }
        public virtual DbSet<Company_News> Company_News { get; set; }
        public virtual DbSet<Company_Profile> Company_Profile { get; set; }
        public virtual DbSet<Contact_US> Contact_US { get; set; }
        public virtual DbSet<InBanner> InBanners { get; set; }
        public virtual DbSet<Industry_News> Industry_News { get; set; }
        public virtual DbSet<InTeam> InTeams { get; set; }
        public virtual DbSet<ProductCenter> ProductCenters { get; set; }
        public virtual DbSet<ProductCenterDetail> ProductCenterDetails { get; set; }
        public virtual DbSet<ProductCenterModel> ProductCenterModels { get; set; }
        public virtual DbSet<Recruitment> Recruitments { get; set; }
        public virtual DbSet<Service_Concept> Service_Concept { get; set; }
        public virtual DbSet<Staff_Presence> Staff_Presence { get; set; }
        public virtual DbSet<SysUser> SysUsers { get; set; }
        public virtual DbSet<Talent_Concept> Talent_Concept { get; set; }
    
        public virtual int Common_FastPageList(string sql, Nullable<int> page, Nullable<int> pageSize, ObjectParameter pageCount, ObjectParameter recordCount)
        {
            var sqlParameter = sql != null ?
                new ObjectParameter("sql", sql) :
                new ObjectParameter("sql", typeof(string));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("page", page) :
                new ObjectParameter("page", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Common_FastPageList", sqlParameter, pageParameter, pageSizeParameter, pageCount, recordCount);
        }
    }
}
